# Generated by Django 5.1 on 2024-09-04 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('text', models.CharField(max_length=250, unique=True, verbose_name='Question Text')),
            ],
        ),
        migrations.CreateModel(
            name='BasePlanMemoire',
            fields=[
                ('memoire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.memoire')),
            ],
            bases=('memoire.memoire',),
        ),
        migrations.CreateModel(
            name='PremiumPlanMemoire',
            fields=[
                ('memoire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.memoire')),
            ],
            bases=('memoire.memoire',),
        ),
        migrations.CreateModel(
            name='QuestionAnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Question Order')),
                ('question_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.question', verbose_name='Question Chosen')),
            ],
        ),
        migrations.CreateModel(
            name='BasePlanAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.answer')),
                ('text', models.TextField(max_length=2000, verbose_name='Answer Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.question', verbose_name='Question Answered')),
            ],
            bases=('memoire.answer',),
        ),
        migrations.CreateModel(
            name='PremiumPlanAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.answer')),
                ('text', models.TextField(max_length=4000, verbose_name='Answer Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.question', verbose_name='Question Answered')),
            ],
            bases=('memoire.answer',),
        ),
        migrations.CreateModel(
            name='BasePlanQuestionAnswerSet',
            fields=[
                ('questionanswerset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.questionanswerset')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.baseplananswer', verbose_name='Answer to Question')),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.baseplanmemoire', verbose_name='Memoire Belonging to')),
            ],
            bases=('memoire.questionanswerset',),
        ),
        migrations.CreateModel(
            name='PremiumPlanQuestionAnswerSet',
            fields=[
                ('questionanswerset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memoire.questionanswerset')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.premiumplananswer', verbose_name='Answer to Question')),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.premiumplanmemoire', verbose_name='Memoire Belonging to')),
            ],
            bases=('memoire.questionanswerset',),
        ),
    ]
